import { Inter, Montserrat } from "next/font/google";
import { Provider } from "../provider";
import { NavMenu } from "../components/(components)/NavMenu";
import { Footer } from "../components/(components)/Footer"
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ variants: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "PersonalWeb By VaioZaffana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`w-full min-h-screen bg-darkGray ${montserrat.className}`}>
          <Provider>
            <NavMenu />
            {children}
            <Footer />
          </Provider>
      </body>
    </html>
  );
}
